[[rulesets]]
group = "ğŸ‡¬ Google"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Google.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Proxy.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/DirectDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/DirectIP.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/DirectProcess.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ’° Binance"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Binance.list"

[[rulesets]]
group = "ğŸ’° Binance"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Binance.list"

[[rulesets]]
group = "ğŸ’° Binance"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Crypto.list"

[[rulesets]]
group = "ğŸ¤– AIæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/AI.list"

[[rulesets]]
group = "ğŸ¤– AIæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"

[[rulesets]]
group = "ï£¿ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ï£¿ è‹¹æœæœåŠ¡"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt,86400"

[[rulesets]]
group = "ï£¿ è‹¹æœæœåŠ¡"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt,86400"

[[rulesets]]
group = "ğŸ‡¬ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "ğŸ‡¬ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

[[rulesets]]
group = "ğŸ‡¬ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list"

[[rulesets]]
group = "ğŸ‡¬ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wechat.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ExaAlice/Alice/main/Rule/DIRECT.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt,86400"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt,86400"

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Youtube.list"

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "ğŸ‘¨â€ğŸ’»â€ Github"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list"

[[rulesets]]
group = "ğŸ‘¨â€ğŸ’»â€ Github"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ’¬ è‡ªç”±æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ’¬ è‡ªç”±æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Telegram.list"

[[rulesets]]
group = "ğŸ’¬ è‡ªç”±æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ExaAlice/Alice/main/Rule/TELEGRAM.list"

[[rulesets]]
group = "ğŸ’¬ è‡ªç”±æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list"

[[rulesets]]
group = "ğŸ’¬ è‡ªç”±æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Discord.list"

[[rulesets]]
group = "ğŸ’¬ è‡ªç”±æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list"

[[rulesets]]
group = "ğŸ† AdBlock"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "ğŸ† AdBlock"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "ğŸ† AdBlock"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"

[[rulesets]]
group = "ğŸ† AdBlock"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt,86400"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIpV6.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOSITE,CN"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

